version: '3'

services:
  db:
    restart: on-failure
    image: 'postgres:latest'
    #env_file: .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME} 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      #- POSTGRES_DB=blog_backend
      #- POSTGRES_PASSWORD=blog_backend
      #- POSTGRES_USER=blog_backend
    labels:
      - traefik.enable=true
      
  blog:
    restart: on-failure
    build: .
    ports:
      - '3000:3000'
    image: "090660780783.dkr.ecr.eu-central-1.amazonaws.com/blog"

  traefik:
    restart: on-failure
    image: 'traefik:latest'
    ports:
      - '80:80'
      - '8080:8080'
      - '443:443'
    command: --api.insecure=true --providers.docker
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock:ro
